"""Run all provider/condition combinations for Prompt A."""

import argparse
import html
import json
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).parent


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--episodes", type=Path, default=ROOT / "episodes.json")
    parser.add_argument("--timeout", type=int, default=120)
    parser.add_argument("--dashboard-url")
    args = parser.parse_args()
    output_dir = ROOT / "results"
    output_dir.mkdir(exist_ok=True)
    for provider in ("codex", "claude"):
        for memory in (False, True):
            condition = "memory" if memory else "baseline"
            command = [
                sys.executable,
                str(ROOT / "run_experiment.py"),
                provider,
                "--episodes",
                str(args.episodes),
                "--timeout",
                str(args.timeout),
                "--output",
                str(output_dir / f"{provider}-{condition}.json"),
            ]
            if args.dashboard_url:
                command.extend(["--dashboard-url", args.dashboard_url])
            if memory:
                command.append("--memory")
            print(f"Running {provider} {condition}...", flush=True)
            result = subprocess.run(command, cwd=ROOT, capture_output=True, text=True)
            if result.returncode:
                error = result.stderr.strip() or result.stdout.strip() or f"exit {result.returncode}"
                (output_dir / f"{provider}-{condition}.json").write_text(json.dumps({
                    "provider": provider, "condition": condition,
                    "status": "failed", "error": error,
                }, indent=2) + "\n")
                print(f"  failed: {error.splitlines()[-1]}", flush=True)

    rows = []
    for path in sorted(output_dir.glob("*.json")):
        data = json.loads(path.read_text())
        if data.get("status") == "failed":
            rows.append(f"| {data['provider']} | {data['condition']} | failed | — | {data['error'].splitlines()[-1]} |")
            continue
        solved = sum(episode["success"] for episode in data["episodes"])
        calls = sum(episode["calls"] for episode in data["episodes"])
        memory = ", ".join(map(str, data.get("remembered_goals", []))) or "—"
        condition = "memory" if data["memory"] else "baseline"
        gifs = ", ".join(f"[{episode['episode']}](gifs/{Path(episode['gif']).name})" for episode in data["episodes"] if episode.get("gif")) or "—"
        rows.append(f"| {data['provider']} | {condition} | {solved}/{len(data['episodes'])} | {calls} | {memory} | {gifs} |")
    (output_dir / "summary.md").write_text("""# Prompt A results

Generated by `run_all.py`. `calls` counts one model decision and tool execution; failed boundary moves are included.

| Provider | Condition | Episodes solved | Total calls | Remembered goals | GIFs |
| --- | --- | ---: | ---: | --- | --- |
""" + "\n".join(rows) + "\n")

    cards = []
    for path in sorted(output_dir.glob("*.json")):
        data = json.loads(path.read_text())
        title = f"{data['provider']} · {data['condition']}"
        if data.get("status") == "failed":
            cards.append(f"<article><h2>{html.escape(title)}</h2><p class='failed'>{html.escape(data['error'].splitlines()[-1])}</p></article>")
            continue
        gifs = "".join(
            f"<figure><img src='{html.escape(episode['gif'])}' alt='Episode {episode['episode']} decision trace'><figcaption>Episode {episode['episode']} · {episode['calls']} calls</figcaption></figure>"
            for episode in data["episodes"] if episode.get("gif")
        )
        solved = sum(episode["success"] for episode in data["episodes"])
        calls = sum(episode["calls"] for episode in data["episodes"])
        memory = html.escape(", ".join(map(str, data.get("remembered_goals", []))) or "none")
        cards.append(f"<article><h2>{html.escape(title)}</h2><p><b>{solved}/{len(data['episodes'])}</b> solved · <b>{calls}</b> calls</p><p class='memory'>Memory: {memory}</p><div class='gifs'>{gifs}</div></article>")
    (output_dir / "index.html").write_text("""<!doctype html><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>Prompt A results</title><style>
body{margin:0;background:#f4efe5;color:#25231f;font:16px system-ui;max-width:1100px;padding:48px;margin:auto}h1,h2{font-family:Georgia,serif}h1{font-size:48px;margin:0 0 8px}header{margin-bottom:32px;color:#756e62}main{display:grid;gap:18px}article{background:#fffaf1;border:1px solid #d8cdbb;padding:20px}h2{margin:0 0 10px}.memory{color:#756e62;font-size:14px}.gifs{display:flex;gap:12px;overflow:auto}figure{margin:0;min-width:150px}img{display:block;width:150px;border:1px solid #d8cdbb}figcaption{font-size:12px;color:#756e62;margin-top:5px}.failed{color:#a24f42;white-space:pre-wrap}</style><header><h1>Does memory help?</h1><div>Prompt A · decision traces and measured results</div></header><main>""" + "\n".join(cards) + "</main>\n")


if __name__ == "__main__":
    main()
