"""Run all provider/condition combinations for Prompt A."""

import argparse
import json
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).parent


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--episodes", type=Path, default=ROOT / "episodes.json")
    parser.add_argument("--timeout", type=int, default=120)
    parser.add_argument("--dashboard-url")
    args = parser.parse_args()
    output_dir = ROOT / "results"
    output_dir.mkdir(exist_ok=True)
    for provider in ("codex", "claude"):
        for memory in (False, True):
            condition = "memory" if memory else "baseline"
            command = [
                sys.executable,
                str(ROOT / "run_experiment.py"),
                provider,
                "--episodes",
                str(args.episodes),
                "--timeout",
                str(args.timeout),
                "--output",
                str(output_dir / f"{provider}-{condition}.json"),
            ]
            if args.dashboard_url:
                command.extend(["--dashboard-url", args.dashboard_url])
            if memory:
                command.append("--memory")
            print(f"Running {provider} {condition}...", flush=True)
            result = subprocess.run(command, cwd=ROOT, capture_output=True, text=True)
            if result.returncode:
                error = result.stderr.strip() or result.stdout.strip() or f"exit {result.returncode}"
                (output_dir / f"{provider}-{condition}.json").write_text(json.dumps({
                    "provider": provider, "condition": condition,
                    "status": "failed", "error": error,
                }, indent=2) + "\n")
                print(f"  failed: {error.splitlines()[-1]}", flush=True)

    rows = []
    for path in sorted(output_dir.glob("*.json")):
        data = json.loads(path.read_text())
        if data.get("status") == "failed":
            rows.append(f"| {data['provider']} | {data['condition']} | failed | — | {data['error'].splitlines()[-1]} |")
            continue
        solved = sum(episode["success"] for episode in data["episodes"])
        calls = sum(episode["calls"] for episode in data["episodes"])
        memory = ", ".join(map(str, data.get("remembered_goals", []))) or "—"
        condition = "memory" if data["memory"] else "baseline"
        rows.append(f"| {data['provider']} | {condition} | {solved}/{len(data['episodes'])} | {calls} | {memory} |")
    (output_dir / "summary.md").write_text("""# Prompt A results

Generated by `run_all.py`. `calls` counts one model decision and tool execution; failed boundary moves are included.

| Provider | Condition | Episodes solved | Total calls | Remembered goals |
| --- | --- | ---: | ---: | --- |
""" + "\n".join(rows) + "\n")


if __name__ == "__main__":
    main()
